version: '3.9'

services:
  paperlessrest:
    container_name: paperlessrest  
    image: paperlessrest:latest  
    build:
      context: .
      dockerfile: PaperlessREST/Dockerfile
      args:
        BUILD_CONFIGURATION: Release  
    ports:
      - "8081:8081"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=PaperlessDB;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=https://+:8081
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://+:8081
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/app/certs/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=MySecurePassword123!
    volumes:
      - ./PaperlessREST/certs:/app/certs  
    depends_on:
      - postgresdb
    networks:
      - app-network

  postgresdb:
    container_name: postgresdb  
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=PaperlessDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"  
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
