server.name: "paperless-kibana"
server.host: "0.0.0.0"
server.publicBaseUrl: "http://localhost:5601"

elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  requestTimeout: 30000
  shardTimeout: 30000

kibana:
  defaultAppId: "discover"
  index: ".kibana"

monitoring.ui.container.elasticsearch.enabled: true
telemetry.enabled: false

# Security settings
xpack:
  security:
    enabled: false
  reporting:
    enabled: true
  spaces:
    enabled: true

# --------------------------------------------------
# 	Kibana logging as of 16.01.2025
# --------------------------------------------------
logging:
  root:
    # Valid options: 'fatal', 'error', 'warn', 'info', 'debug', 'trace', 'all'
    level: "warn"
  quiet: true   # If 'true', Kibana won’t write all logs to stdout
  useUTC: true
