# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  paperlessrest:
    build:
      context: "C:\\Users\\anfh2\\Desktop\\Paperless\\Paperless\\Paperless"
      dockerfile: "PaperlessREST/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/PaperlessREST.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/PaperlessREST.staticwebassets.runtime.CT.json"
    image: "paperlessrest:dev"
    ports: []
    volumes:
    - "C:\\Users\\anfh2\\Desktop\\Paperless\\Paperless\\Paperless\\PaperlessREST:/app:rw"
    - "C:\\Users\\anfh2\\Desktop\\Paperless\\Paperless\\Paperless:/src:rw"
    - "C:\\Users\\anfh2\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
